name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt cache and install joblib
      run: |
        pip install joblib==1.2.0
        pip show joblib
    - name: Deploy to GitHub Pages
      uses: fastai/workflows/quarto-ghp@master